Repository boostcampwm-2022/iOS11-Doesaegim, pull requests merged in 2022-12, with the labels that each got.

#118 [다이어리 목록] 다이어리 목록 버그 수정
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListHeaderView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
Labels: 다이어리 목록, bugfix

#120 [얼굴 인식] 탐지 데이터 뷰컨트롤러 전송, 얼굴 선택 인터렉션
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/DetectedFaceCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController+CollectionView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/TempMosaicViewController.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+.swift
Labels: feature, 얼굴인식

#117 [추가 화면] 추가하는 화면에 기능 추가
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIViewController+PresentAlert.swift
Labels: feature

#121 [커스텀 그래프] 막대 그래프 및 애니메이션 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseChartView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarBackgroundLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarShapeLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarTextLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/CustomBarChart.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
  Doesaegim/Doesaegim/Utility/ExpenseType.swift
Labels: feature, 그래프

#123 [커스텀 캘린더] 일요일 날짜 Label이 붉은색으로 나타나지 않는 오류 수정
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellViewModel.swift
Labels: bugfix

#124 [얼굴 인식] 블러 처리 기능 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/BlurredImageViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/TempMosaicViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/BlurredImageViewModel.swift
  Doesaegim/Doesaegim/Services/ShareManager.swift
  Doesaegim/Doesaegim/Utility/Extensions/CIImage+Filters.swift
Labels: feature, 얼굴인식

#125 [리팩토링] 알림추가, 고차함수사용, 이미지디테일 -> 얼굴인식 화면 연결
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryPhotoDetail/DiaryPhotoDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/FaceDetectViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/DetectedFaceCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/FaceDetectViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ExpenseListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ExpenseTravelViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/TravelListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
Labels: refactoring

#126 [Refactoring] MKMapView의 메모리 낭비
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
Labels: refactoring, MapKit

#110 [Firebase] Firebase Crashlytics 연동
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Doesaegim/Doesaegim.xcodeproj/xcshareddata/xcschemes/Doesaegim.xcscheme
  Doesaegim/Doesaegim/App/AppDelegate.swift
  Doesaegim/Doesaegim/App/GoogleService-Info.plist
Labels: feature

#128 [App] 앱 아이콘 추가
  Doesaegim/Doesaegim/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  Doesaegim/Doesaegim/App/Assets.xcassets/AppIcon.appiconset/Doesaegim_AppIcon.png
Labels: App Icon

#130 [여행 추가] 여행 추가 관련 리팩토링
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
  Doesaegim/Doesaegim/Repository/TravelScene/TravelAdd/TravelAddLocalRepository.swift
  Doesaegim/Doesaegim/Repository/TravelScene/TravelAdd/TravelAddRepository.swift
  Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewSubtitleLabel.swift
  Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewTextField.swift
Labels: refactoring

#131 [커스텀 그래프 리팩토링] 버그 일부 수정 및 리팩토링
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseChartView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/CustomBarChart.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartType.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceShapeLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceTextLayer.swift
Labels: 그래프, refactoring

#135 [일정 추가] 일정 추가 관련 리팩토링
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/PlanDTO.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddLocalRepository.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanAdd/PlanAddRepository.swift
  Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewCompleteButton.swift
  Doesaegim/Doesaegim/Utility/Custom/AddViewComponents/AddViewInputButton.swift
Labels: refactoring

#133 [다이어리 목록] 다이어리 셀과 헤더가 매칭되지 않는 버그 수정
  Doesaegim/Doesaegim/Data/ViewModel/DiaryInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Labels: bug, 다이어리 목록, bugfix

#132 [리팩토링] 이미지 메모리캐시 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Services/FileProcessManager.swift
  Doesaegim/Doesaegim/Services/ImageCacheManager.swift
Labels: refactoring

#136 [설정화면] 설정화면의 기본적인 UI구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/SettingOptionViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/View/SettingTableViewCell.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/View/SettingViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/ViewModel/SettingViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/ViewModel/SettingViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
Labels: feature

#137 [리팩토링] 다이어리 상세 조회 리팩토링
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DetailImageCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/ImageSlider/View/ImageSliderView.swift
Labels: refactoring, bugfix, 다이어리 조회

#140 [리팩토링] 다이어리 리스트 튜플에서 구조체로 변경
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/TravelDiaryViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
Labels: 다이어리 목록, refactoring

#139 [일정 목록] 리팩토링
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
  Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift
Labels: feature, refactoring

#141 feat: FileProcessManager에서 이미지 저장 시 압축 방식 변경
  Doesaegim/Doesaegim/Services/FileProcessManager.swift
Labels: feature

#143 [리팩토링] 지출 추가 + PickerView
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeData.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeResponse.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/Protocol/ExpenseAddPickerViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/Protocol/ExpenseAddPickerViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/View/ExpenseAddPickerViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ViewModel/ExpenseAddPickerViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/Exchange/ExchangeRemoteRepository.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/Exchange/ExchangeRepository.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddLocalRepository.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddRepository.swift
  Doesaegim/Doesaegim/Utility/Enum/ExchangeRateType.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Labels: bug, refactoring

#146 [커스텀 캘린더] 리팩토링 및 UI 개선
  Doesaegim/Doesaegim/App/Assets.xcassets/ColorSets/calendarOrange.colorset/Contents.json
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIColor+.swift
Labels: refactoring

#145 [다이어리 작성] 날짜 선택 기능 추가 및 리팩토링
  Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/PickerDataSource.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
Labels: feature, refactoring

#150 [지도화면] 애노테이션이 나타나지 않는 버그 수정
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/ViewModel/MapViewModel.swift
Labels: bugfix, 맵뷰

#175 다크모드 방지
  Doesaegim/Doesaegim/App/Info.plist
Labels: feature

#152 [다이어리 작성] 사용성 개선
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/ProgressiveImageCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
  Doesaegim/Doesaegim/Utility/Enum/ImageStatus.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+SystemImages.swift
Labels: feature

#176 [지출 추가] 화폐 단위 입력시 Int overflow로 인해 크래시나는 부분 수정
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
Labels: bug

#177 [일정목록] 이름, 내용 줄 수 제한 및 날짜 표시 방식 변경 #173 #174
  Doesaegim/Doesaegim/Data/PlanListSnapshotData.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/PlanListViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/CheckBox.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/DateCollectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+Formatter.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift
Labels: feature

#179 [지출 목록 조회] 관련 이슈 수정
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpensePlaceholdView.swift
Labels: bugfix, 지출목록

#178 [지출 추가] 환율 정보 (일본, 인도네시아) 부정확한 환율 버그 수정
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeData.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
Labels: bugfix

#181 [커스텀 캘린더] 일요일 관련 버그 해결
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellViewModel.swift
Labels: feature, 캘린더, bugfix

#180 [여행목록, 지출화면-여행목록] 셀 재정의
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/TravelExpenseInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ExpenseTravelViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
Labels: feature

#182 [다이어리 조회] 표시할 텍스트가 nil일 때 히든 처리 및 날짜 표시 설정 반영
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
Labels: bugfix, 다이어리 조회

#185 [설정화면] 라이센스
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/Setting/LibraryInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/CalendarSetting/ViewModel/CalendarSettingViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/License/LicenseViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/License/View/LibraryCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/License/View/LibraryViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/License/ViewModel/LibraryViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/License/ViewModel/LibraryViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingMain/ViewModel/SettingViewModel.swift
Labels: feature, 설정화면

#187 [지출 목록 조회] 섹션 헤더 버그 수정 및 설정 화면의 날짜 표시 방식 반영
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
Labels: bugfix, 지출목록

#188 [다이어리 편집] 편집 관련 기능 개선
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
  Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModel.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Labels: feature

#189 [설정화면] 개인정보 처리방침, 문의하기, 푸시알림 토글
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/App/SceneDelegate.swift
  Doesaegim/Doesaegim/Data/ViewModel/SettingOptionViewModel.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/CalendarSetting/View/CalendarSettingController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/CalendarSetting/ViewModel/CalendarSettingViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/Library/View/LibraryCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/Library/View/LibraryViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/Library/ViewModel/LibraryViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/Library/ViewModel/LibraryViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingMain/View/SettingSwitchCell.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingMain/View/SettingViewController.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingMain/ViewModel/SettingViewModel.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingMain/ViewModel/SettingViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Utility/Enum/UserDefaultsKey.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+Formatter.swift
  Doesaegim/Doesaegim/Utility/Extensions/UserDefaults+.swift
Labels: feature, 설정화면

#192 [얼굴 인식] 블러 처리 버그 해결 및 기능 개선 #155
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/DetectInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryPhotoDetail/DiaryPhotoDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/FaceDetectViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/BlurredImageViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/BlurredImageViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/FaceDetectViewModel.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIImage/UIImage+Downsample.swift
Labels: feature

#193 [다이어리 작성, 편집] 장소 삭제 기능 추가
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/View/DiaryEditViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryEdit/ViewModel/DiaryEditViewModel.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditLocalRepository.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryEdit/DiaryEditRepository.swift
Labels: feature

#194 [지출 목록] 지출 셀, 헤더 디자인, 삭제기능 추가
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ExpenseListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/SettingScene/Library/View/LibraryCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Utility/Extensions/UICollectionViewCell+Shadow.swift
Labels: feature

#196 [삭제 기능] 여행, 다이어리 삭제
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Labels: feature, 삭제

#195 [장소 검색] 검색 결과가 없을 때 검색 실패 alert이 뜨는 현상 수정
  Doesaegim/Doesaegim/Repository/TravelScene/SearchingLocation/SearchingLocationRemoteRepository.swift
Labels: bugfix, 장소검색

#197 [지출 수정] 지출 상세화면 및 수정 기능 구현
  Doesaegim/Doesaegim/App/Doesaegim.xcdatamodeld/Doesaegim.xcdatamodel/contents
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/ExpenseDTO.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddLocalRepository.swift
  Doesaegim/Doesaegim/Repository/ExpenseScene/ExpenseAdd/ExpenseAddRepository.swift
  Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift
Labels: feature

#198 [커스텀 그래프] 버그 수정
  Doesaegim/Doesaegim/Utility/CustomGraph/BarChart/BarTextLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
Labels: 그래프, bugfix

#199 [다이어리 목록] 일정 변경사항이 바로 적용되도록 변경
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/PlanAddViewControllerDelegate.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/PlanListViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
Labels: feature

#200 [지출 목록] 지출 목록에 금액 (지출 액수 * 환율) 값으로 표기되도록 변경
  Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarHeaderView.swift
  Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift
Labels: feature

#204 hotfix: 블러처리 뷰에서 공유하기 버튼 누락 문제 해결
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/BlurredImageViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/BlurredImageViewModel.swift
Labels: bug

#206 refactor: 일정 목록 fetchBatchSize 변경
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
Labels: refactoring

#205 feat: 세로모드로 고정
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/App/Info.plist
Labels: feature

#207 docs: README 작성
  README.md
Labels: documentation
