Repository boostcampwm-2022/iOS11-Doesaegim, pull requests merged in 2022-11, with the labels that each got.

#26 [일정 목록] 일정 목록 UI 구현 #10
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/CheckBox.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/DateCollectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/EmptyLabeledCollectionView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
  Doesaegim/Doesaegim/Utility/Constants.swift
  Doesaegim/Doesaegim/Utility/Extensions/String+Placeholders.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIColor+.swift
  Doesaegim/Doesaegim/Utility/Extensions/UILabel+ChangeFontSize.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIStackView+AddArrangedSubviews.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIView+AddSubviews.swift
Labels: feature

#28 [장소 추가] 장소 추가 화면 UI 및 MapKit 검색 결과 표시 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchResultCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewControllerDelegate.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/ViewModel/SearchResultCellViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/ViewModel/SearchingLocationViewModel.swift
Labels: feature

#31 [일정 목록] 코어데이터와 일정 목록 연동 #13
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/PlanDTO.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/EmptyLabeledCollectionView.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanViewModel.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
  Doesaegim/Doesaegim/Utility/CoreDataError.swift
  Doesaegim/Doesaegim/Utility/Extensions/NSObject+Name.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIViewController+PresentAlert.swift
  Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift
Labels: feature

#33 [여행목록, 지출 여행목록] Core Data 페이지네이션 구현, UIContentConfiguration 적용
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ExpenseTravelViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/TravelListControllerProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/TravelListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelCollectionViewCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
  Doesaegim/Doesaegim/Services/PersistentManager.swift
  Doesaegim/NSManagedObjectClass/Travel+CoreDataClass.swift
Labels: feature

#34 [일정 목록] 일정 삭제 #21
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
  Doesaegim/Doesaegim/Utility/CoreDataError.swift
Labels: feature

#35 [일정 추가] 일정 추가 UI 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/CalendarProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/CalendarViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Labels: feature

#39 [장소 추가] 장소 검색 화면에서 선택한 장소를 일정 추가화면으로 보내도록 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationViewControllerDelegate.swift
Labels: feature

#40 [일정 목록] 코어데이터 호출 방식 변경 및 여행 목록, 일정 추가 화면과 연결 #13, #15
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim.xcodeproj/xcshareddata/xcschemes/Doesaegim.xcscheme
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanLocalRepository.swift
  Doesaegim/Doesaegim/Repository/TravelScene/PlanList/PlanRepository.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIScrollView+DidPassPoint.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift
  Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift
Labels: feature

#41 [여행 목록, 지출 여행목록, 지출 목록] 커스텀 셀 생성, 스타일, 헤더등록
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpensePlaceholdView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListCell.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
Labels: feature

#43 [여행추가] 리팩토링 및 버그 수정
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
  Doesaegim/Doesaegim/Utility/Custom/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Labels: feature

#44 [지출 목록] 지출목록 글로벌헤더와 섹션헤더의 분리
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ExpenseListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseSectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/ViewModel/ExpenseTravelViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
  Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepository.swift
  Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepositoryProtocol.swift
  Doesaegim/Doesaegim/Services/PersistentManager.swift
  Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift
Labels: feature

#74 [일정 추가] 일정 추가 기능 구현
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/ViewModel/PlanAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/ViewModel/PlanListViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/View/TravelListViewController.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Labels: feature

#78 [다이어리 작성] UI 구현 #77
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift
Labels: feature

#79 [지출관리 - 지출화면 조회] 커스텀 원형 그래프 구현 및 지출 조회 화면에서 표시
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceShapeLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceTextLayer.swift
  Doesaegim/Doesaegim/Utility/ExpenseType.swift
Labels: feature

#80 [지도 화면] 지도 출력, 핀 콜아웃 출력
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/DiaryMapInfoViewModel.swift
  Doesaegim/Doesaegim/Data/ViewModel/ExpenseInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListCell.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/MapViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/DiaryAnnotation.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/TempDiaryViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/ViewModel/MapViewModel.swift
  Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepository.swift
  Doesaegim/Doesaegim/Repository/PersistentStorage/PersistentRepositoryProtocol.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Labels: feature

#81 [지출 추가] 지출추가 화면 미흡한 점 개선 및 환율 정보 API 연동 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeResponse.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Services/NetworkManager.swift
  Doesaegim/Doesaegim/Utility/Constants.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarHeaderView.swift
  Doesaegim/Doesaegim/Utility/Custom/PickerView/PickerViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/PickerView/PickerViewProtocol.swift
  Doesaegim/Doesaegim/Utility/Enum/ExchangeRateType.swift
  Doesaegim/Doesaegim/Utility/Extensions/String/String+ConvertRemoveComma.swift
  Doesaegim/Doesaegim/Utility/Extensions/String/String+Placeholders.swift
  Doesaegim/Doesaegim/Utility/Extensions/UIViewController+SetRightBarPlusButton.swift
  Doesaegim/Doesaegim/Utility/Resource/Resource.swift
Labels: feature

#82 [지출 추가] 환율 조회 캐시 구현 및 지출 추가시 CoreData 저장 기능 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/ExpenseDTO.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/Model/ExchangeResponse.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddView.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/ViewModel/ExpenseAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListCell.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseListViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/ViewModel/ExpenseListViewModel.swift
  Doesaegim/Doesaegim/Utility/Constants.swift
  Doesaegim/Doesaegim/Utility/Custom/PickerView/PickerViewProtocol.swift
  Doesaegim/Doesaegim/Utility/ExpenseType.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
  Doesaegim/NSManagedObjectClass/Expense+CoreDataClass.swift
Labels: feature

#83 [다이어리 작성] 여행, 장소, 제목, 내용 입력
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
  Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/PlaceSearchButton.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/PickerDataSource.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/SearchingLocation/View/SearchingLocationView.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAddLocalRepository.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAddRepository.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
  Doesaegim/NSManagedObjectClass/Location+CoreDataClass.swift
Labels: feature

#89 [다이어리 조회] 다이어리 상세 화면 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DetailImageCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DetailImageCellViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModelDelegate.swift
  Doesaegim/Doesaegim/Repository/DiaryDetailScene/DiaryDetail/DiaryDetailLocalRepository.swift
  Doesaegim/Doesaegim/Repository/DiaryDetailScene/DiaryDetail/DiaryDetailRepository.swift
Labels: feature

#93 [다이어리 목록, 맵과 다이어리 연동] 데모용 PR
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/ViewModel/DiaryInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/DiaryListViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListHeaderView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryViewController.swift
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/ViewModel/MapViewModel.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelList/ViewModel/TravelListViewModel.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Labels: 데모

#107 [다이어리 목록] 셀, 헤더 디자인 변경
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/App/Doesaegim.xcdatamodeld/Doesaegim.xcdatamodel/contents
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListHeaderView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/View/DiaryListViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/DiaryAnnotation.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/MapViewController.swift
  Doesaegim/Doesaegim/Presentation/MapScene/MapViewScene/View/TempDiaryViewController.swift
  Doesaegim/Doesaegim/Utility/Extensions/String/String+Truncate.swift
Labels: feature, 다이어리 목록

#106 [환율 조회] 버그 해결 및 네트워크 통신 리팩토링
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/PickerView/ExpenseAddPickerViewController.swift
  Doesaegim/Doesaegim/Services/NetworkManager.swift
Labels: feature

#108 [커스텀 캘린더] 캘린더 기능 추가
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseAdd/View/ExpenseAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanAdd/View/PlanAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/PlanList/View/PlanListViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewController.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/View/TravelAddViewProtocol.swift
  Doesaegim/Doesaegim/Presentation/TravelScene/TravelAdd/ViewModel/TravelAddViewModel.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CalendarViewController.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCell.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellProtocol.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendarCellViewModel.swift
  Doesaegim/Doesaegim/Utility/Extensions/Date/Date+TravelString.swift
Labels: feature, 캘린더

#111 [리팩토링 및 버그 수정] 다이어리 조회, 그래프 이슈 수정
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/View/DiaryDetailViewController.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseList/View/ExpenseCollectionHeaderView.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/CustomChartItem.swift
Labels: bug, refactoring

#112 [다이어리 작성] 저장 기능 구현 #68
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/Data/DTO/PersistentDTO/DiaryDTO.swift
  Doesaegim/Doesaegim/Data/DTO/TemporaryDiary.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/DiaryAddViewController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/View/TranslucentActivityIndicatorView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryAdd/ViewModel/DiaryAddViewModelDelegate.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryDetail/ViewModel/DiaryDetailViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/DiaryList/ViewModel/DiaryListViewModel.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryDetail/DiaryDetailLocalRepository.swift
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryDetail/DiaryDetailRepository.swift
  Doesaegim/Doesaegim/Services/FileProcessManager.swift
  Doesaegim/NSManagedObjectClass/Diary+CoreDataClass.swift
Labels: feature

#113 [다이어리 작성] 여행 피커 순서를 종료 날짜 최신순으로 변경 #53
  Doesaegim/Doesaegim/Repository/DiaryScene/DiaryAdd/DiaryAddLocalRepository.swift
  Doesaegim/NSManagedObjectClass/Plan+CoreDataClass.swift
  Doesaegim/NSManagedObjectClass/Travel+CoreDataClass.swift
Labels: feature

#115 [얼굴 인식] Vision 로직 작성, 컬렉션 뷰 추가
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/App/Assets.xcassets/face_example.imageset/Contents.json
  Doesaegim/Doesaegim/App/Assets.xcassets/face_example.imageset/face_example.jpeg
  Doesaegim/Doesaegim/App/Assets.xcassets/monalisa.imageset/Contents.json
  Doesaegim/Doesaegim/App/Assets.xcassets/monalisa.imageset/monalisa.jpeg
  Doesaegim/Doesaegim/Data/ViewModel/DetectInfoViewModel.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/FaceDetectViewModelProtocol.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/DetectedFaceCell.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController+CollectionView.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/View/FaceDetectController.swift
  Doesaegim/Doesaegim/Presentation/DiaryScene/FaceDetection/ViewModel/FaceDetectViewModel.swift
  Doesaegim/Doesaegim/Presentation/ExpenseScene/ExpenseTravelList/View/ExpenseTravelListController.swift
  Doesaegim/Doesaegim/Presentation/MainTabBarController.swift
  Doesaegim/Doesaegim/Utility/Extensions/CGImagePropertyOrientation/CGImagePropertyOrientation+.swift
Labels: feature, 얼굴인식

#116 [커스텀 그래프] 원형 그래프 애니메이션 구현
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/CustomPieChart.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceShapeLayer.swift
  Doesaegim/Doesaegim/Utility/CustomGraph/PieChart/PieceTextLayer.swift
Labels: feature, 그래프, refactoring

#114 [공유하기] 이미지 공유 기능 구현
  Doesaegim/Doesaegim.xcodeproj/project.pbxproj
  Doesaegim/Doesaegim/App/Info.plist
  Doesaegim/Doesaegim/Presentation/SettingScene/SettingViewController.swift
  Doesaegim/Doesaegim/Services/ShareManager.swift
  Doesaegim/Doesaegim/Utility/Custom/Calendar/CustomCalendar.swift
Labels: feature
